### ISSUE TITLE
Deb pkgs broken

### ISSUE THREAD

**Issue by rlex** [go-graphite/carbonapi#258]
Subj, when trying to update today (autobuild repo):
```
dpkg: error processing archive /var/cache/apt/archives/carbonapi_ba289_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'carbonapi':
 error in 'Version' field string 'ba289': version number does not start with digit
Errors were encountered while processing:
 /var/cache/apt/archives/carbonapi_ba289_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by joemiller** [comment]
Ran into this too. Need the autobuilds over the versioned builds for the merged carbonzipper support.

My unsolicited recommendation (that I'm borrowing from other projects) would be for the autobuild versions to be prefixed with current version + short git hash so that they always begin with a digit:
```
$(git describe --abbrev=4 --dirty --always --tags)+$(git rev-parse --short HEAD)
0.9.0+f00baz

**Comment by Civil** [comment]
Found the problem, travis some time ago started to clone repo with --depth=50, and we are almost 100 commits ahead of latest tag :)

Should be fixed in master.

I'll also clean all broken packages (or at least will try to do that)

**Comment by Civil** [comment]
carbonapi_0.8.0-96-g995997_amd64.deb
carbonapi-0.8.0-97.g995997.x86_64.rpm
