### ISSUE TITLE
Where can i find the srpm for carbonapi?

### ISSUE THREAD

**Issue by patsevanton** [go-graphite/carbonapi#275]
Hello!
I try build carbonapi to rpm, but i dont see srpm or spec file.
Where can i find the srpm for carbonapi?
Thank you

**Comment by azhiltsov** [comment]
As it is a golang code it compiled differently. 
We already have RPM on packagecloud
https://packagecloud.io/go-graphite/stable/install#bash-rpm

**Comment by patsevanton** [comment]
I run `curl -s https://packagecloud.io/install/repositories/go-graphite/stable/script.rpm.sh | sudo bash `
go-graphite_stable.repo have go-graphite_stable-source
```
[go-graphite_stable-source]
name=go-graphite_stable-source
baseurl=https://packagecloud.io/go-graphite/stable/el/7/SRPMS
repo_gpgcheck=1
gpgcheck=0
enabled=0
gpgkey=https://packagecloud.io/go-graphite/stable/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
```
But dont have srpm in this repo.

**Comment by Civil** [comment]
Packages for that repo were generated with 'fpm' (http://fpm.readthedocs.io/en/latest/intro.html). It doesn't produce srpm, it doesn't produce specs. You can find the bash script that executes fpm here: https://github.com/go-graphite/carbonapi/blob/master/contrib/fpm/create_package_rpm.sh

It should be possible to construct spec file based on that.

Feel free to write your own spec file and make a PR with that. Though I'll continue to use fpm to build packages, because it's more convenient for Go programs.

**Comment by patsevanton** [comment]
Thank you
