### ISSUE TITLE
Memory usage high and not decreasing

### ISSUE THREAD

**Issue by timvandermeij** [go-graphite/carbonapi#400]
First of all, thank you for your work on `carbonapi`!

I'm in the process of combining `carbonapi` with `go-carbon`. If I understood correctly, `carbonapi` implements (a subset of) the Graphite API for fetching metrics from an underlying data storage, in my case `go-carbon` with Whisper files.

Therefore, I would expect temporary memory usage spikes for `carbonapi` if it needs to process the data from `go-carbon` with the Graphite functions. However, so far I have never seen memory usage of the `carbonapi` process decrease, nor is it within reasonable limits. I'm currently experiencing the `carbonapi` process using 20+ GB of memory. Not only does this never decrease, but it also doesn't increase in the way I would expect. If I do a query on many metrics (after glob expansion 90000) after restarting the process, the memory usage stays at a few GB at most. Then, after a short white without any activity, memory usage rapidly increases to the 20+ GB. This is the part that confuses me the most; what is it doing at that moment?

In short, do you:
- have ideas about what may cause memory usage to grow rapidly all of a sudden without any user interaction (queries);
- have ideas about why memory usage never decreases after the query has been processed;
- have suggestions on how I can keep memory usage of the `carbonapi` process within reasonable limits (I think 8 GB should be the maximum), i.e., what settings should I tweak for this.

My `carbonapi.yaml` file is the default file with the cache type set to `null` to disable the cache in an attempt to reduce memory usage (setting `size_mb` didn't help at all for memory usage, so I'm assuming it's not the cache that's the problem) and `sendGlobsAsIs` set to `true` in an attempt to let `go-carbon` take care of glob expansion and to reduce calls to `go-carbon`.

Any suggestions for improving the situation are very much appreciated!

**Comment by Civil** [comment]
I would suspect that it's related to:
https://golang.org/doc/go1.12#runtime
and this discussion:
https://www.reddit.com/r/golang/comments/aw4uai/anyone_seeing_memory_issues_in_112/

And if it is - this is just the way how golang 1.12 now works (also in that case, this memory is not really in-use, but is marked as MADV_FREE, so OS it's freed, but not zeroed-out by OS, and that's why it's counted as "used", therefore technically it is not)

However if you want to know that for sure, I'd suggest to obtain pprof memory dump:
https://golang.org/doc/diagnostics.html#profiling - see Heap profile.

Pprof is usually exposed at `/debug/pprof/` url.

Obtaining SVG for all allocation should show where it actually happens.

And sudden memory consumption might be related to heavy queries or a high number of parallel queries. You might get some idea if you'll look at the access.log as there was an attempt to record an approximate memory allocation per query (it's unfortunately approximate).

Currently there is no way to limit carbonapi's memory consumption overall. You can try to put it into it's own cgroup with hard limit of 8 GB, but in case there will be queries that will require more - OOM killer might kill it.

**Comment by timvandermeij** [comment]
This has been very helpful; thank you! I'm going to look into this, so I'm closing the ticket as answered for now.
