### ISSUE TITLE
Custom backend

### ISSUE THREAD

**Issue by jonasbleyl** [go-graphite/carbonapi#427]
Is it possible to write a custom backend to our existing database?

We currently use graphite-web and have written a custom Finder to our database which controls how graphite queries our database.

Is there something similar to this with carbonapi or is this not within the scope of the project?

**Comment by Civil** [comment]
It is possible, however not as a plugin.

All currently supported protocols (closest representation of custom Finder) are stored here:
https://github.com/go-graphite/carbonapi/tree/master/zipper/protocols

Unfortunately there is not a lot of documentation available about how to write your custom protocol. But basically you need to create a package there. Package must have init that will register protocol. You can use https://github.com/go-graphite/carbonapi/blob/master/zipper/protocols/graphite/graphite_group.go#L25-L34 as an example

Interface that it must satisfy is here:
https://github.com/go-graphite/carbonapi/blob/master/zipper/types/interface.go#L15-L33

Also you need to register all available protocols which is done by importing them in zipper.go:
https://github.com/go-graphite/carbonapi/blob/master/zipper/zipper.go#L17-L22

I understand that it's far from ideal, but creating a proper and usable plugins in Go is very troublesome and that's why I haven't bothered with documentation on how to write custom protocol.

But if you'll decide to take that path and if you'll have any further questions - I can try to answer them.

P.S. I haven't touched interfaces for a while, but as I'm not aware about any forks of carbonapi that implements custom protocols, I'm making changes to that parts without any prior notices and without marking them as breaking changes in Changelog.

**Comment by arodland** [comment]
Yes, it's possible. I've done it, and it's working well. The code is unfortunately not publicly available but it was pretty easy for me. I imported the `carbonapi_v3_pb` package and just implemented the `/metrics/find` and `/render` endpoints, which are sufficient for the basics. `/metrics/find` needs to query available metrics and return a `GlobResponse`, and `/render` needs to return a `MultiFetchResponse` containing some `FetchResponse`s, which are pretty straightforwardly filled with raw values. I wrote a (short, not-very-technical) [blog post](https://medium.com/@arodland/an-interesting-thing-i-did-with-graphite-6cddd93c1364) about it back in 2017.

**Comment by Civil** [comment]
Oh, right. That's another approach is to just make your server talk carbonapi_v3_pb and return it straight out of your database.

Depends on what is easier for you.

I think actually @arodland approach is better in terms of maintenance as you won't need to make a Pull Request with the code only(?) you will use.

Btw, for the reference you can use https://github.com/go-graphite/carbonapi/blob/master/cmd/mockbackend/main.go - which is single-file "mock" backend I'm using to reproduce various issues reported here. It reads yaml file with response and provide /metrics/find and /render APIs to query that from carbonapi.

**Comment by jonasbleyl** [comment]
Nice, both of those solutions sound like they will work well. I agree that @arodland's solution will be better long term so I will attempt that first and see how it works for us.

Thank you both for the very thorough answers!
