### ISSUE TITLE
add support for noNullPoints

### ISSUE THREAD

**Issue by exsver** [go-graphite/carbonapi#445]
From graphite Docs:
"noNullPoints
Default: False
If set and combined with format=json, removes all null datapoints from the series returned."

https://graphite.readthedocs.io/en/latest/render_api.html#nonullpoints

**Comment by s3rj1k** [comment]
@Civil Why you are closing issues without mentioning that fixes are in latest release?

**Comment by deniszh** [comment]
I think @Civil closing issue when merging to master, and it doesn't mean release. Release is done separately, with changelog mentioned in release notes.

**Comment by s3rj1k** [comment]
@deniszh I noticed that it was added in changelog.

I meant that it's hard to track everything and double check that closed issues were actually closed because issue was fixed.

My point was that saying that this issue was closed because it was implemented and merged to master would be super nice for people that do actually track progress if this.

There was no intention to be disrespectful.

Thanks.

**Comment by Civil** [comment]
Issue is closed automatically by github, whenever I mention in the commit "Fixes" and bug number. Basically starting from that point it would be included in all autobuilds. For which version will have the issue - I'm trying not to do a point release with new features (not that it cannot happen though) so likely it will be included in a next major release.

Unfortunately even though it's suboptimal, but I have no automation here to close issues once the major version that contains the commit has been tagged. However if you know hot to do something like that using only opensource-friendly software or projects (e.x. I'm currently building packages with travis) you can link an article here or even send a PR that will add such automation. The only requirement I have is that this thing shouldn't include any self-hosted scripts, as I don't want to rely on my home NAS to trigger those builds at this moment.
