### ISSUE TITLE
Functions not displayed in Grafana

### ISSUE THREAD

**Issue by just4blood** [go-graphite/carbonapi#460]
Hello all,

I can't see some functions in Grafana for example groupByNodes, groupByTags.
Also the functions that are carbonapi only like movingAverage
Is there a way to add them from config file?
I am using carbonapi 0.12.6

Thank you!

**Comment by Civil** [comment]
Can you please share the config file you are currently using for carbonapi?

Also how's the graphite datasource configured in grafana and what version of grafana you are using?

But overall, if you don't have graphiteweb09compat option enabled (https://github.com/go-graphite/carbonapi/blob/master/cmd/carbonapi/carbonapi.example.yaml#L212) and if you've configured datasource version in grafana to be 1.1.x, then Grafana should be able to automatically get full list of supported functions from carbonapi. Otherwise it'll fall back to whatever default set was specified for graphite-web-0.9.x (that could explain why you don't see groupByTags there)

**Comment by just4blood** [comment]
`
listen:  "0.0.0.0:8081"
prefix: ""
expvar:
  enabled: true
  pprofEnabled: false
  listen: ""
headersToPass:
  - "X-Dashboard-Id"
  - "X-Grafana-Org-Id"
  - "X-Panel-Id"
headersToLog:
  - "X-Dashboard-Id"
  - "X-Grafana-Org-Id"
  - "X-Panel-Id"
define:
  -
    name: "perMinute"
    template:  "perSecond({{.argString}})|scale(60)"
notFoundStatusCode: 404
concurency: 10000
cpus: 0
tz: ""
functionsConfig:
    graphiteWeb: /etc/graphiteWeb.yaml
maxBatchSize: 10000
graphite:
    host: "localhost:2003"
    interval: "60s"
    prefix: "carbon.api"
    pattern:  "{prefix}.{fqdn}"
idleConnections: 10
pidFile: ""
upstreams:
    buckets: 10
    timeouts:
        find: "30s"
        render: "60s"
        connect: "200ms"
    concurrencyLimitPerServer: 0
    keepAliveInterval: "30s"
    maxIdleConnsPerHost: 100
    backends:
          - "{{ carbon1 }}"
          - "{{ carbon2 }}"
          - "{{ carbon3 }}"

    carbonsearch:
        backend: "http://127.0.0.1:8070"
        prefix: "virt.v1.*"
    carbonsearchv2:
        # Carbonsearch instances. Follows the same syntax as backendsv2
        backends:
            -
              groupName: "group1"
              protocol: "carbonapi_v3_pb"
              lbMethod: "broadcast"
              servers:
                  - "{{ carbon1 }}"
                  - "{{ carbon2 }}"
                  - "{{ carbon3 }}"

        # carbonsearch prefix to reserve/register
        prefix: "virt.v1.*"

    graphite09compat: false
graphTemplates: /etc/graphTemplates.yaml
expireDelaySec: 10
logger:
    - logger: ""
      file: "stderr"
      level: "debug"
      encoding: "console"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
    - logger: ""
      file: "/var/log/carbonapi/carbonapi.log"
      level: "info"
      encoding: "json"
tagdb:
      url: "http://127.0.0.1:9090"
`

Graphite datasource is configured with version 1.1.x, Grafana version is 6.6.2

Thank you!

**Comment by just4blood** [comment]
I have changed the datasource in Grafana to 0.9 and then back to 1.1.x and it shows all the functions now.
