### ISSUE TITLE
Headers not passed forward in render request

### ISSUE THREAD

**Issue by jonasbleyl** [go-graphite/carbonapi#485]
Headers are not passed forward in render requests, but they are passed in find requests.

Example config:
```
headersToPass:
  - "X-Grafana-User"
```

This worked in version 0.12.5 but no longer works in the latest version 0.13.0

**Comment by Civil** [comment]
TLDR; Fixed in current master.

However I likely will bump version to 0.14.0 because of the fix. Main reason is that to properly fix the issue, I've decided to pass context around all the Eval* related functions (`Eval`, `EvalExpr`, `RewriteExpr`, and all the functions in `expr/functions`) and that technically breaks API for other projects that might use `expr`. One that I know about is moira-alert/moira and that's why @borovskyav might be interested in that changes if he'll update their vendor to use current version of carbonapi. Not sure though if they have any plans for that.

**Comment by jonasbleyl** [comment]
Perfect, thanks @Civil!
