### ISSUE TITLE
[BUG] No log rotate for RPM builds

### ISSUE THREAD

**Issue by Hipska** [go-graphite/carbonapi#573]
There seems to be no log rotate config shipped for RPM, while there is a config for DEB packages: https://github.com/go-graphite/carbonapi/blob/main/contrib/carbonapi/deb/carbonapi.logrotate

**Comment by Civil** [comment]
I think I forgot to add it when I was fixing previous build problems (there are other smaller problems, like no sha in build names for autobuilds).

However I don't really know what to do with RPMs in light of what happened with CentOS

**Comment by Hipska** [comment]
What do you mean? CentOS and RHEL will still use rpm as package format afaik.

**Comment by Civil** [comment]
As far as I understand current news, CentOS 7 and 8 will no longer be updated, instead focusing on bleeding edge sort of rolling-release CentOS Streams. So I don't know what to use instead of CentOS to build for RHEL 7/8.

**Comment by Civil** [comment]
That should be fixed in `carbonapi-0.15.2~57+sha.gbb33f2`

Please reopen if that still doesn't work.

P.S. Not sure if that matters for you, but I was sort of forced to drop support for centos-6 as it's broken again and there is seems to be no easy workaround the problem (linker fails with internal error)
P.S.S. I'm also open for suggestions what to use instead of centos8 for building the packages. Would really appreciate some pointers here (maybe in terms of docker image that I can use instead of centos:8)
