### ISSUE TITLE
[FR] Drop user privileges

### ISSUE THREAD

**Issue by tleuxner** [go-graphite/carbonapi#599]
**Is your feature request related to a problem? Please describe.**
Currently **carbonapi** starts its service as root under _systemd_.

**Describe the solution you'd like**
Carbonapi should drop elevated privileges and run under an unprivileged user.

**Additional context**
My current workaround is to use an override for systemd. However I reckon a general setting for all init platforms would be a better approach.

**/etc/systemd/system/carbonapi.service.d/override.conf**
```
[Service]
User=carbon
Group=carbon
```

**Comment by Civil** [comment]
Problem here is that this change seems to be a breaking one (or potentially breaking one) as people who use packages already will need to have some migration path (as an obvious problem - logs will be owned by root).

I'm also not really sure how to properly handle all of that with `nfpm` (I use it instead of proper package files to build packages).

Otherwise - yeah, that's a good point of course and eventually should be changed to a less privileged user.

**Comment by Civil** [comment]
That will be fixed once the https://github.com/go-graphite/helper-scripts/pull/4 will be merged (before next release).
