### ISSUE TITLE
[BUG] aliasByNode should return full name

### ISSUE THREAD

**Issue by ywwg** [go-graphite/carbonapi#836]
**Describe the bug**

for a formula like:
`aliasByNode(keepLastValue(foo.bar.{XX,YY}.baz.alpha, inf), 5)`

Upstream graphite returns the full metric name tag (foo.bar.YY.baz.alpha), but carbonapi is only returning the replacement string (YY).

**Comment by npazosmendez** [comment]
Here's the exact problem:
- In CarbonAPI's `aliasByNode` [we use](https://github.com/go-graphite/carbonapi/blob/d9996b2b74d64013a89b26bad7155b057a3ba148/expr/functions/aliasByNode/function.go#L46) `CopyName` to create the result, which sets the `"name"` tag to match the series' name: https://github.com/go-graphite/carbonapi/blob/d9996b2b74d64013a89b26bad7155b057a3ba148/expr/types/types.go#L491
- GraphiteWeb does not do that, it [only sets the name](https://github.com/graphite-project/graphite-web/blob/0ec7201c42ac2c14485c4c7eaab8a644082dc687/webapp/graphite/render/functions.py#L2760).


I believe this is also a problem for other functions, some I found:
- `aliasSub`
- `aliasQuery`

And other `alias*`. 

Also, I think this issue is the same as what was fixed in https://github.com/go-graphite/carbonapi/pull/801 for `transformNull`

**Comment by npazosmendez** [comment]
Reproduce in graphite web:
- `docker run -d --name graphite -p 80:80 -p 2003:2003 graphiteapp/graphite-statsd`
- ```$ echo "local.random.diceroll 4 `date +%s`" | nc -c 127.0.0.1 2003```
- example for `aliasByNode`: $ curl "http://localhost/render?target=aliasByNode(local.random.diceroll,2)&from=-1min&until=now&format=json&maxDataPoints=1" | jq`
```
[
  {
    "target": "diceroll",
    "tags": {
      "name": "local.random.diceroll"
    },
    "datapoints": [
      [
        null,
        1722443460
      ]
    ]
  }
]
```


- example for `aliasSub`: ```$ curl "http://localhost/render?target=aliasSub(local.random.diceroll,'random','fixed')&from=-1min&until=now&format=json&maxDataPoints=1" | jq```
```
[
  {
    "target": "local.fixed.diceroll",
    "tags": {
      "name": "local.random.diceroll"
    },
    "datapoints": [
      [
        null,
        1722443640
      ]
    ]
  }
]
```
